version: "3"

services:
    # This is the Atlas Backend service [Production]
    production:
        build:
            context: .
        ports:
            - "8081:8080" # Change the host port to 8081
    # Development container service
    development:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
        working_dir: /app
# Additional services can be defined here if needed
