// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: client_server_message.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientToServerMessageType int32

const (
	ClientToServerMessageType_REQUEST_GAME_STATE ClientToServerMessageType = 0
	ClientToServerMessageType_SEND_GAME_UPDATE   ClientToServerMessageType = 1
	ClientToServerMessageType_SEND_CHAT_MESSAGE  ClientToServerMessageType = 2
)

// Enum value maps for ClientToServerMessageType.
var (
	ClientToServerMessageType_name = map[int32]string{
		0: "REQUEST_GAME_STATE",
		1: "SEND_GAME_UPDATE",
		2: "SEND_CHAT_MESSAGE",
	}
	ClientToServerMessageType_value = map[string]int32{
		"REQUEST_GAME_STATE": 0,
		"SEND_GAME_UPDATE":   1,
		"SEND_CHAT_MESSAGE":  2,
	}
)

func (x ClientToServerMessageType) Enum() *ClientToServerMessageType {
	p := new(ClientToServerMessageType)
	*p = x
	return p
}

func (x ClientToServerMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientToServerMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_server_message_proto_enumTypes[0].Descriptor()
}

func (ClientToServerMessageType) Type() protoreflect.EnumType {
	return &file_client_server_message_proto_enumTypes[0]
}

func (x ClientToServerMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientToServerMessageType.Descriptor instead.
func (ClientToServerMessageType) EnumDescriptor() ([]byte, []int) {
	return file_client_server_message_proto_rawDescGZIP(), []int{0}
}

// Client to server message
type ClientToServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType ClientToServerMessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=protobufs.ClientToServerMessageType" json:"message_type,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*ClientToServerMessage_GameUpdatePayload
	//	*ClientToServerMessage_ChatMessagePayload
	Payload isClientToServerMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ClientToServerMessage) Reset() {
	*x = ClientToServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_server_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientToServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToServerMessage) ProtoMessage() {}

func (x *ClientToServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_server_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToServerMessage.ProtoReflect.Descriptor instead.
func (*ClientToServerMessage) Descriptor() ([]byte, []int) {
	return file_client_server_message_proto_rawDescGZIP(), []int{0}
}

func (x *ClientToServerMessage) GetMessageType() ClientToServerMessageType {
	if x != nil {
		return x.MessageType
	}
	return ClientToServerMessageType_REQUEST_GAME_STATE
}

func (m *ClientToServerMessage) GetPayload() isClientToServerMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ClientToServerMessage) GetGameUpdatePayload() *GameUpdatePayload {
	if x, ok := x.GetPayload().(*ClientToServerMessage_GameUpdatePayload); ok {
		return x.GameUpdatePayload
	}
	return nil
}

func (x *ClientToServerMessage) GetChatMessagePayload() *ChatMessagePayload {
	if x, ok := x.GetPayload().(*ClientToServerMessage_ChatMessagePayload); ok {
		return x.ChatMessagePayload
	}
	return nil
}

type isClientToServerMessage_Payload interface {
	isClientToServerMessage_Payload()
}

type ClientToServerMessage_GameUpdatePayload struct {
	GameUpdatePayload *GameUpdatePayload `protobuf:"bytes,3,opt,name=game_update_payload,json=gameUpdatePayload,proto3,oneof"`
}

type ClientToServerMessage_ChatMessagePayload struct {
	ChatMessagePayload *ChatMessagePayload `protobuf:"bytes,4,opt,name=chat_message_payload,json=chatMessagePayload,proto3,oneof"`
}

func (*ClientToServerMessage_GameUpdatePayload) isClientToServerMessage_Payload() {}

func (*ClientToServerMessage_ChatMessagePayload) isClientToServerMessage_Payload() {}

var File_client_server_message_proto protoreflect.FileDescriptor

var file_client_server_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x1a, 0x1a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8e, 0x02, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x4e, 0x0a, 0x13, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00,
	0x52, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x51, 0x0a, 0x14, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x48, 0x00, 0x52, 0x12, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x2a, 0x60, 0x0a, 0x19, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x12, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x47,
	0x41, 0x4d, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x53, 0x45, 0x4e, 0x44, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47,
	0x45, 0x10, 0x02, 0x42, 0x22, 0x5a, 0x20, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2d, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_server_message_proto_rawDescOnce sync.Once
	file_client_server_message_proto_rawDescData = file_client_server_message_proto_rawDesc
)

func file_client_server_message_proto_rawDescGZIP() []byte {
	file_client_server_message_proto_rawDescOnce.Do(func() {
		file_client_server_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_server_message_proto_rawDescData)
	})
	return file_client_server_message_proto_rawDescData
}

var file_client_server_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_server_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_client_server_message_proto_goTypes = []interface{}{
	(ClientToServerMessageType)(0), // 0: protobufs.ClientToServerMessageType
	(*ClientToServerMessage)(nil),  // 1: protobufs.ClientToServerMessage
	(*GameUpdatePayload)(nil),      // 2: protobufs.GameUpdatePayload
	(*ChatMessagePayload)(nil),     // 3: protobufs.ChatMessagePayload
}
var file_client_server_message_proto_depIdxs = []int32{
	0, // 0: protobufs.ClientToServerMessage.message_type:type_name -> protobufs.ClientToServerMessageType
	2, // 1: protobufs.ClientToServerMessage.game_update_payload:type_name -> protobufs.GameUpdatePayload
	3, // 2: protobufs.ClientToServerMessage.chat_message_payload:type_name -> protobufs.ChatMessagePayload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_client_server_message_proto_init() }
func file_client_server_message_proto_init() {
	if File_client_server_message_proto != nil {
		return
	}
	file_game_message_payload_proto_init()
	file_chat_message_payload_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_client_server_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientToServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_client_server_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientToServerMessage_GameUpdatePayload)(nil),
		(*ClientToServerMessage_ChatMessagePayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_server_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_server_message_proto_goTypes,
		DependencyIndexes: file_client_server_message_proto_depIdxs,
		EnumInfos:         file_client_server_message_proto_enumTypes,
		MessageInfos:      file_client_server_message_proto_msgTypes,
	}.Build()
	File_client_server_message_proto = out.File
	file_client_server_message_proto_rawDesc = nil
	file_client_server_message_proto_goTypes = nil
	file_client_server_message_proto_depIdxs = nil
}
