// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: game_message_payload.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload for game state
type GameStatePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Define your game state fields here
	Level         int32  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	IsStarted     bool   `protobuf:"varint,2,opt,name=is_started,json=isStarted,proto3" json:"is_started,omitempty"`
	IsOver        bool   `protobuf:"varint,3,opt,name=is_over,json=isOver,proto3" json:"is_over,omitempty"`
	CurrentLetter string `protobuf:"bytes,4,opt,name=currentLetter,proto3" json:"currentLetter,omitempty"`
}

func (x *GameStatePayload) Reset() {
	*x = GameStatePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_message_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatePayload) ProtoMessage() {}

func (x *GameStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_message_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatePayload.ProtoReflect.Descriptor instead.
func (*GameStatePayload) Descriptor() ([]byte, []int) {
	return file_game_message_payload_proto_rawDescGZIP(), []int{0}
}

func (x *GameStatePayload) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GameStatePayload) GetIsStarted() bool {
	if x != nil {
		return x.IsStarted
	}
	return false
}

func (x *GameStatePayload) GetIsOver() bool {
	if x != nil {
		return x.IsOver
	}
	return false
}

func (x *GameStatePayload) GetCurrentLetter() string {
	if x != nil {
		return x.CurrentLetter
	}
	return ""
}

// Payload for game update
type GameUpdatePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Define minimal version of game state here
	Level int32  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GameUpdatePayload) Reset() {
	*x = GameUpdatePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_message_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameUpdatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUpdatePayload) ProtoMessage() {}

func (x *GameUpdatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_game_message_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUpdatePayload.ProtoReflect.Descriptor instead.
func (*GameUpdatePayload) Descriptor() ([]byte, []int) {
	return file_game_message_payload_proto_rawDescGZIP(), []int{1}
}

func (x *GameUpdatePayload) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GameUpdatePayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_game_message_payload_proto protoreflect.FileDescriptor

var file_game_message_payload_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x10, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72,
	0x22, 0x3d, 0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42,
	0x22, 0x5a, 0x20, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_message_payload_proto_rawDescOnce sync.Once
	file_game_message_payload_proto_rawDescData = file_game_message_payload_proto_rawDesc
)

func file_game_message_payload_proto_rawDescGZIP() []byte {
	file_game_message_payload_proto_rawDescOnce.Do(func() {
		file_game_message_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_message_payload_proto_rawDescData)
	})
	return file_game_message_payload_proto_rawDescData
}

var file_game_message_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_message_payload_proto_goTypes = []interface{}{
	(*GameStatePayload)(nil),  // 0: protobufs.GameStatePayload
	(*GameUpdatePayload)(nil), // 1: protobufs.GameUpdatePayload
}
var file_game_message_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_message_payload_proto_init() }
func file_game_message_payload_proto_init() {
	if File_game_message_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_message_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStatePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_message_payload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameUpdatePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_message_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_message_payload_proto_goTypes,
		DependencyIndexes: file_game_message_payload_proto_depIdxs,
		MessageInfos:      file_game_message_payload_proto_msgTypes,
	}.Build()
	File_game_message_payload_proto = out.File
	file_game_message_payload_proto_rawDesc = nil
	file_game_message_payload_proto_goTypes = nil
	file_game_message_payload_proto_depIdxs = nil
}
