// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: other_payloads.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRoomPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	GameKind    string `protobuf:"bytes,2,opt,name=game_kind,json=gameKind,proto3" json:"game_kind,omitempty"`
	TurnMode    string `protobuf:"bytes,3,opt,name=turn_mode,json=turnMode,proto3" json:"turn_mode,omitempty"`
}

func (x *JoinRoomPayload) Reset() {
	*x = JoinRoomPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_payloads_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomPayload) ProtoMessage() {}

func (x *JoinRoomPayload) ProtoReflect() protoreflect.Message {
	mi := &file_other_payloads_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomPayload.ProtoReflect.Descriptor instead.
func (*JoinRoomPayload) Descriptor() ([]byte, []int) {
	return file_other_payloads_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRoomPayload) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *JoinRoomPayload) GetGameKind() string {
	if x != nil {
		return x.GameKind
	}
	return ""
}

func (x *JoinRoomPayload) GetTurnMode() string {
	if x != nil {
		return x.TurnMode
	}
	return ""
}

type OnConnectAckPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    string            `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId  string            `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameKind  string            `protobuf:"bytes,3,opt,name=game_kind,json=gameKind,proto3" json:"game_kind,omitempty"`
	Room      *RoomSnapshot     `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	GameState *GameStatePayload `protobuf:"bytes,5,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	TurnMode  string            `protobuf:"bytes,6,opt,name=turn_mode,json=turnMode,proto3" json:"turn_mode,omitempty"`
}

func (x *OnConnectAckPayload) Reset() {
	*x = OnConnectAckPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_payloads_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnConnectAckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnConnectAckPayload) ProtoMessage() {}

func (x *OnConnectAckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_other_payloads_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnConnectAckPayload.ProtoReflect.Descriptor instead.
func (*OnConnectAckPayload) Descriptor() ([]byte, []int) {
	return file_other_payloads_proto_rawDescGZIP(), []int{1}
}

func (x *OnConnectAckPayload) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *OnConnectAckPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *OnConnectAckPayload) GetGameKind() string {
	if x != nil {
		return x.GameKind
	}
	return ""
}

func (x *OnConnectAckPayload) GetRoom() *RoomSnapshot {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *OnConnectAckPayload) GetGameState() *GameStatePayload {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *OnConnectAckPayload) GetTurnMode() string {
	if x != nil {
		return x.TurnMode
	}
	return ""
}

type RoomSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId                string        `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	GameKind              string        `protobuf:"bytes,2,opt,name=game_kind,json=gameKind,proto3" json:"game_kind,omitempty"`
	Status                string        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MaxPlayers            int32         `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	IsStarted             bool          `protobuf:"varint,5,opt,name=is_started,json=isStarted,proto3" json:"is_started,omitempty"`
	CreatedAt             string        `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt             string        `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiresAt             string        `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Players               []*PlayerData `protobuf:"bytes,9,rep,name=players,proto3" json:"players,omitempty"`
	TurnMode              string        `protobuf:"bytes,10,opt,name=turn_mode,json=turnMode,proto3" json:"turn_mode,omitempty"`
	CurrentTurnPlayerId   string        `protobuf:"bytes,11,opt,name=current_turn_player_id,json=currentTurnPlayerId,proto3" json:"current_turn_player_id,omitempty"`
	CurrentTurnPlayerName string        `protobuf:"bytes,12,opt,name=current_turn_player_name,json=currentTurnPlayerName,proto3" json:"current_turn_player_name,omitempty"`
	TurnIndex             int32         `protobuf:"varint,13,opt,name=turn_index,json=turnIndex,proto3" json:"turn_index,omitempty"`
}

func (x *RoomSnapshot) Reset() {
	*x = RoomSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_payloads_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSnapshot) ProtoMessage() {}

func (x *RoomSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_other_payloads_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSnapshot.ProtoReflect.Descriptor instead.
func (*RoomSnapshot) Descriptor() ([]byte, []int) {
	return file_other_payloads_proto_rawDescGZIP(), []int{2}
}

func (x *RoomSnapshot) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomSnapshot) GetGameKind() string {
	if x != nil {
		return x.GameKind
	}
	return ""
}

func (x *RoomSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoomSnapshot) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomSnapshot) GetIsStarted() bool {
	if x != nil {
		return x.IsStarted
	}
	return false
}

func (x *RoomSnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoomSnapshot) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RoomSnapshot) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *RoomSnapshot) GetPlayers() []*PlayerData {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomSnapshot) GetTurnMode() string {
	if x != nil {
		return x.TurnMode
	}
	return ""
}

func (x *RoomSnapshot) GetCurrentTurnPlayerId() string {
	if x != nil {
		return x.CurrentTurnPlayerId
	}
	return ""
}

func (x *RoomSnapshot) GetCurrentTurnPlayerName() string {
	if x != nil {
		return x.CurrentTurnPlayerName
	}
	return ""
}

func (x *RoomSnapshot) GetTurnIndex() int32 {
	if x != nil {
		return x.TurnIndex
	}
	return 0
}

type ServerErrorPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ServerErrorPayload) Reset() {
	*x = ServerErrorPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_payloads_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerErrorPayload) ProtoMessage() {}

func (x *ServerErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_other_payloads_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerErrorPayload.ProtoReflect.Descriptor instead.
func (*ServerErrorPayload) Descriptor() ([]byte, []int) {
	return file_other_payloads_proto_rawDescGZIP(), []int{3}
}

func (x *ServerErrorPayload) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServerErrorPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoomUpdatePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *RoomSnapshot `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *RoomUpdatePayload) Reset() {
	*x = RoomUpdatePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_payloads_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomUpdatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUpdatePayload) ProtoMessage() {}

func (x *RoomUpdatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_other_payloads_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUpdatePayload.ProtoReflect.Descriptor instead.
func (*RoomUpdatePayload) Descriptor() ([]byte, []int) {
	return file_other_payloads_proto_rawDescGZIP(), []int{4}
}

func (x *RoomUpdatePayload) GetRoom() *RoomSnapshot {
	if x != nil {
		return x.Room
	}
	return nil
}

var File_other_payloads_proto protoreflect.FileDescriptor

var file_other_payloads_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x73, 0x1a, 0x11, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x6e, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x6f, 0x64, 0x65,
	0x22, 0xee, 0x01, 0x0a, 0x13, 0x4f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x63,
	0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x72,
	0x6f, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x3a, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x6f, 0x64,
	0x65, 0x22, 0xd4, 0x03, 0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x67, 0x61, 0x6d, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x12, 0x2f, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x33, 0x0a, 0x16, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x37, 0x0a, 0x18, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x75, 0x72, 0x6e,
	0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x15, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x75, 0x72, 0x6e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x75, 0x72,
	0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74,
	0x75, 0x72, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x42, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x40, 0x0a, 0x11,
	0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x42, 0x22,
	0x5a, 0x20, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_other_payloads_proto_rawDescOnce sync.Once
	file_other_payloads_proto_rawDescData = file_other_payloads_proto_rawDesc
)

func file_other_payloads_proto_rawDescGZIP() []byte {
	file_other_payloads_proto_rawDescOnce.Do(func() {
		file_other_payloads_proto_rawDescData = protoimpl.X.CompressGZIP(file_other_payloads_proto_rawDescData)
	})
	return file_other_payloads_proto_rawDescData
}

var file_other_payloads_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_other_payloads_proto_goTypes = []interface{}{
	(*JoinRoomPayload)(nil),     // 0: protobufs.JoinRoomPayload
	(*OnConnectAckPayload)(nil), // 1: protobufs.OnConnectAckPayload
	(*RoomSnapshot)(nil),        // 2: protobufs.RoomSnapshot
	(*ServerErrorPayload)(nil),  // 3: protobufs.ServerErrorPayload
	(*RoomUpdatePayload)(nil),   // 4: protobufs.RoomUpdatePayload
	(*GameStatePayload)(nil),    // 5: protobufs.GameStatePayload
	(*PlayerData)(nil),          // 6: protobufs.PlayerData
}
var file_other_payloads_proto_depIdxs = []int32{
	2, // 0: protobufs.OnConnectAckPayload.room:type_name -> protobufs.RoomSnapshot
	5, // 1: protobufs.OnConnectAckPayload.game_state:type_name -> protobufs.GameStatePayload
	6, // 2: protobufs.RoomSnapshot.players:type_name -> protobufs.PlayerData
	2, // 3: protobufs.RoomUpdatePayload.room:type_name -> protobufs.RoomSnapshot
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_other_payloads_proto_init() }
func file_other_payloads_proto_init() {
	if File_other_payloads_proto != nil {
		return
	}
	file_player_data_proto_init()
	file_game_message_payload_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_other_payloads_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_payloads_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnConnectAckPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_payloads_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_payloads_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerErrorPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_payloads_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomUpdatePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_other_payloads_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_other_payloads_proto_goTypes,
		DependencyIndexes: file_other_payloads_proto_depIdxs,
		MessageInfos:      file_other_payloads_proto_msgTypes,
	}.Build()
	File_other_payloads_proto = out.File
	file_other_payloads_proto_rawDesc = nil
	file_other_payloads_proto_goTypes = nil
	file_other_payloads_proto_depIdxs = nil
}
