// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: payloads.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C2S Payloads
type PlayerJoinGamePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
}

func (x *PlayerJoinGamePayload) Reset() {
	*x = PlayerJoinGamePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerJoinGamePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinGamePayload) ProtoMessage() {}

func (x *PlayerJoinGamePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinGamePayload.ProtoReflect.Descriptor instead.
func (*PlayerJoinGamePayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerJoinGamePayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type ReconnectPlayerPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *ReconnectPlayerPayload) Reset() {
	*x = ReconnectPlayerPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnectPlayerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectPlayerPayload) ProtoMessage() {}

func (x *ReconnectPlayerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectPlayerPayload.ProtoReflect.Descriptor instead.
func (*ReconnectPlayerPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{1}
}

func (x *ReconnectPlayerPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ToggleReadyStatePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsReady bool `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
}

func (x *ToggleReadyStatePayload) Reset() {
	*x = ToggleReadyStatePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleReadyStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleReadyStatePayload) ProtoMessage() {}

func (x *ToggleReadyStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleReadyStatePayload.ProtoReflect.Descriptor instead.
func (*ToggleReadyStatePayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{2}
}

func (x *ToggleReadyStatePayload) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type StartGamePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *StartGamePayload) Reset() {
	*x = StartGamePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGamePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGamePayload) ProtoMessage() {}

func (x *StartGamePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGamePayload.ProtoReflect.Descriptor instead.
func (*StartGamePayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{3}
}

func (x *StartGamePayload) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type SubmitWordPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *SubmitWordPayload) Reset() {
	*x = SubmitWordPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitWordPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWordPayload) ProtoMessage() {}

func (x *SubmitWordPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWordPayload.ProtoReflect.Descriptor instead.
func (*SubmitWordPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitWordPayload) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type UsePowerUpPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PowerUpType PowerUpType `protobuf:"varint,1,opt,name=power_up_type,json=powerUpType,proto3,enum=protobufs.PowerUpType" json:"power_up_type,omitempty"`
}

func (x *UsePowerUpPayload) Reset() {
	*x = UsePowerUpPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsePowerUpPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePowerUpPayload) ProtoMessage() {}

func (x *UsePowerUpPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePowerUpPayload.ProtoReflect.Descriptor instead.
func (*UsePowerUpPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{5}
}

func (x *UsePowerUpPayload) GetPowerUpType() PowerUpType {
	if x != nil {
		return x.PowerUpType
	}
	return PowerUpType_POWER_UP_TYPE_UNSPECIFIED
}

type ChatMessagePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ChatMessagePayload) Reset() {
	*x = ChatMessagePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessagePayload) ProtoMessage() {}

func (x *ChatMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessagePayload.ProtoReflect.Descriptor instead.
func (*ChatMessagePayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMessagePayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// S2C Payloads
type OnConnectAckPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	IsHost   bool   `protobuf:"varint,3,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
}

func (x *OnConnectAckPayload) Reset() {
	*x = OnConnectAckPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnConnectAckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnConnectAckPayload) ProtoMessage() {}

func (x *OnConnectAckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnConnectAckPayload.ProtoReflect.Descriptor instead.
func (*OnConnectAckPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{7}
}

func (x *OnConnectAckPayload) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *OnConnectAckPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *OnConnectAckPayload) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

type PlayerJoinedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerData *PlayerData `protobuf:"bytes,1,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
}

func (x *PlayerJoinedPayload) Reset() {
	*x = PlayerJoinedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerJoinedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinedPayload) ProtoMessage() {}

func (x *PlayerJoinedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinedPayload.ProtoReflect.Descriptor instead.
func (*PlayerJoinedPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerJoinedPayload) GetPlayerData() *PlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

type PlayerLeftPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *PlayerLeftPayload) Reset() {
	*x = PlayerLeftPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLeftPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeftPayload) ProtoMessage() {}

func (x *PlayerLeftPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeftPayload.ProtoReflect.Descriptor instead.
func (*PlayerLeftPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerLeftPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PlayerDataUpdatePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerData *PlayerData `protobuf:"bytes,1,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
}

func (x *PlayerDataUpdatePayload) Reset() {
	*x = PlayerDataUpdatePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerDataUpdatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDataUpdatePayload) ProtoMessage() {}

func (x *PlayerDataUpdatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDataUpdatePayload.ProtoReflect.Descriptor instead.
func (*PlayerDataUpdatePayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerDataUpdatePayload) GetPlayerData() *PlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

type GameStartedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category            string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	StartingLetter      string `protobuf:"bytes,2,opt,name=starting_letter,json=startingLetter,proto3" json:"starting_letter,omitempty"`
	TurnPlayerId        string `protobuf:"bytes,3,opt,name=turn_player_id,json=turnPlayerId,proto3" json:"turn_player_id,omitempty"`
	TurnDurationSeconds int32  `protobuf:"varint,4,opt,name=turn_duration_seconds,json=turnDurationSeconds,proto3" json:"turn_duration_seconds,omitempty"`
}

func (x *GameStartedPayload) Reset() {
	*x = GameStartedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartedPayload) ProtoMessage() {}

func (x *GameStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartedPayload.ProtoReflect.Descriptor instead.
func (*GameStartedPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{11}
}

func (x *GameStartedPayload) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GameStartedPayload) GetStartingLetter() string {
	if x != nil {
		return x.StartingLetter
	}
	return ""
}

func (x *GameStartedPayload) GetTurnPlayerId() string {
	if x != nil {
		return x.TurnPlayerId
	}
	return ""
}

func (x *GameStartedPayload) GetTurnDurationSeconds() int32 {
	if x != nil {
		return x.TurnDurationSeconds
	}
	return 0
}

type TurnChangePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextPlayerId string `protobuf:"bytes,1,opt,name=next_player_id,json=nextPlayerId,proto3" json:"next_player_id,omitempty"`
	LastWord     string `protobuf:"bytes,2,opt,name=last_word,json=lastWord,proto3" json:"last_word,omitempty"`
	NextLetter   string `protobuf:"bytes,3,opt,name=next_letter,json=nextLetter,proto3" json:"next_letter,omitempty"`
}

func (x *TurnChangePayload) Reset() {
	*x = TurnChangePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TurnChangePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnChangePayload) ProtoMessage() {}

func (x *TurnChangePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnChangePayload.ProtoReflect.Descriptor instead.
func (*TurnChangePayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{12}
}

func (x *TurnChangePayload) GetNextPlayerId() string {
	if x != nil {
		return x.NextPlayerId
	}
	return ""
}

func (x *TurnChangePayload) GetLastWord() string {
	if x != nil {
		return x.LastWord
	}
	return ""
}

func (x *TurnChangePayload) GetNextLetter() string {
	if x != nil {
		return x.NextLetter
	}
	return ""
}

type WordValidationResultPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *WordValidationResultPayload) Reset() {
	*x = WordValidationResultPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordValidationResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordValidationResultPayload) ProtoMessage() {}

func (x *WordValidationResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordValidationResultPayload.ProtoReflect.Descriptor instead.
func (*WordValidationResultPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{13}
}

func (x *WordValidationResultPayload) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *WordValidationResultPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GameOverPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinnerPlayerId string           `protobuf:"bytes,1,opt,name=winner_player_id,json=winnerPlayerId,proto3" json:"winner_player_id,omitempty"`
	Scores         map[string]int32 `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GameOverPayload) Reset() {
	*x = GameOverPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOverPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverPayload) ProtoMessage() {}

func (x *GameOverPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverPayload.ProtoReflect.Descriptor instead.
func (*GameOverPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{14}
}

func (x *GameOverPayload) GetWinnerPlayerId() string {
	if x != nil {
		return x.WinnerPlayerId
	}
	return ""
}

func (x *GameOverPayload) GetScores() map[string]int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type ErrorMessagePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorMessagePayload) Reset() {
	*x = ErrorMessagePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessagePayload) ProtoMessage() {}

func (x *ErrorMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessagePayload.ProtoReflect.Descriptor instead.
func (*ErrorMessagePayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{15}
}

func (x *ErrorMessagePayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BroadcastChatMessagePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId string `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *BroadcastChatMessagePayload) Reset() {
	*x = BroadcastChatMessagePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastChatMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastChatMessagePayload) ProtoMessage() {}

func (x *BroadcastChatMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastChatMessagePayload.ProtoReflect.Descriptor instead.
func (*BroadcastChatMessagePayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{16}
}

func (x *BroadcastChatMessagePayload) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *BroadcastChatMessagePayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// The main sync payload
type GameStateSyncPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId             string        `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Category           string        `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	IsStarted          bool          `protobuf:"varint,3,opt,name=is_started,json=isStarted,proto3" json:"is_started,omitempty"`
	IsOver             bool          `protobuf:"varint,4,opt,name=is_over,json=isOver,proto3" json:"is_over,omitempty"`
	TurnPlayerId       string        `protobuf:"bytes,5,opt,name=turn_player_id,json=turnPlayerId,proto3" json:"turn_player_id,omitempty"`
	CurrentLetter      string        `protobuf:"bytes,6,opt,name=current_letter,json=currentLetter,proto3" json:"current_letter,omitempty"`
	LastWord           string        `protobuf:"bytes,7,opt,name=last_word,json=lastWord,proto3" json:"last_word,omitempty"`
	Players            []*PlayerData `protobuf:"bytes,8,rep,name=players,proto3" json:"players,omitempty"`
	TurnStartTimestamp int64         `protobuf:"varint,9,opt,name=turn_start_timestamp,json=turnStartTimestamp,proto3" json:"turn_start_timestamp,omitempty"`
}

func (x *GameStateSyncPayload) Reset() {
	*x = GameStateSyncPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStateSyncPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateSyncPayload) ProtoMessage() {}

func (x *GameStateSyncPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateSyncPayload.ProtoReflect.Descriptor instead.
func (*GameStateSyncPayload) Descriptor() ([]byte, []int) {
	return file_payloads_proto_rawDescGZIP(), []int{17}
}

func (x *GameStateSyncPayload) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameStateSyncPayload) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GameStateSyncPayload) GetIsStarted() bool {
	if x != nil {
		return x.IsStarted
	}
	return false
}

func (x *GameStateSyncPayload) GetIsOver() bool {
	if x != nil {
		return x.IsOver
	}
	return false
}

func (x *GameStateSyncPayload) GetTurnPlayerId() string {
	if x != nil {
		return x.TurnPlayerId
	}
	return ""
}

func (x *GameStateSyncPayload) GetCurrentLetter() string {
	if x != nil {
		return x.CurrentLetter
	}
	return ""
}

func (x *GameStateSyncPayload) GetLastWord() string {
	if x != nil {
		return x.LastWord
	}
	return ""
}

func (x *GameStateSyncPayload) GetPlayers() []*PlayerData {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateSyncPayload) GetTurnStartTimestamp() int64 {
	if x != nil {
		return x.TurnStartTimestamp
	}
	return 0
}

var File_payloads_proto protoreflect.FileDescriptor

var file_payloads_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x1a, 0x11, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x70, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69,
	0x6e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a,
	0x16, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x17, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x2e, 0x0a, 0x10, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x4f, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x55,
	0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3a, 0x0a, 0x0d, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x5f, 0x75, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x50, 0x6f, 0x77, 0x65,
	0x72, 0x55, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x64, 0x0a, 0x13, 0x4f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x41, 0x63, 0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x13, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x36, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x11, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x17, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x36, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0xb3,
	0x01, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x65,
	0x74, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x69, 0x6e, 0x67, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x75,
	0x72, 0x6e, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x32, 0x0a, 0x15, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x13, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x22, 0x77, 0x0a, 0x11, 0x54, 0x75, 0x72, 0x6e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x65, 0x78,
	0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x22, 0x50, 0x0a,
	0x1b, 0x57, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0xb6, 0x01, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3e, 0x0a,
	0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76,
	0x65, 0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x1a, 0x39, 0x0a,
	0x0b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2f, 0x0a, 0x13, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x54, 0x0a, 0x1b, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0xd0, 0x02, 0x0a, 0x14, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x79, 0x6e,
	0x63, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74,
	0x75, 0x72, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x74, 0x74,
	0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x12,
	0x2f, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x12, 0x30, 0x0a, 0x14, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12,
	0x74, 0x75, 0x72, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x75, 0x65, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2d, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_payloads_proto_rawDescOnce sync.Once
	file_payloads_proto_rawDescData = file_payloads_proto_rawDesc
)

func file_payloads_proto_rawDescGZIP() []byte {
	file_payloads_proto_rawDescOnce.Do(func() {
		file_payloads_proto_rawDescData = protoimpl.X.CompressGZIP(file_payloads_proto_rawDescData)
	})
	return file_payloads_proto_rawDescData
}

var file_payloads_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_payloads_proto_goTypes = []interface{}{
	(*PlayerJoinGamePayload)(nil),       // 0: protobufs.PlayerJoinGamePayload
	(*ReconnectPlayerPayload)(nil),      // 1: protobufs.ReconnectPlayerPayload
	(*ToggleReadyStatePayload)(nil),     // 2: protobufs.ToggleReadyStatePayload
	(*StartGamePayload)(nil),            // 3: protobufs.StartGamePayload
	(*SubmitWordPayload)(nil),           // 4: protobufs.SubmitWordPayload
	(*UsePowerUpPayload)(nil),           // 5: protobufs.UsePowerUpPayload
	(*ChatMessagePayload)(nil),          // 6: protobufs.ChatMessagePayload
	(*OnConnectAckPayload)(nil),         // 7: protobufs.OnConnectAckPayload
	(*PlayerJoinedPayload)(nil),         // 8: protobufs.PlayerJoinedPayload
	(*PlayerLeftPayload)(nil),           // 9: protobufs.PlayerLeftPayload
	(*PlayerDataUpdatePayload)(nil),     // 10: protobufs.PlayerDataUpdatePayload
	(*GameStartedPayload)(nil),          // 11: protobufs.GameStartedPayload
	(*TurnChangePayload)(nil),           // 12: protobufs.TurnChangePayload
	(*WordValidationResultPayload)(nil), // 13: protobufs.WordValidationResultPayload
	(*GameOverPayload)(nil),             // 14: protobufs.GameOverPayload
	(*ErrorMessagePayload)(nil),         // 15: protobufs.ErrorMessagePayload
	(*BroadcastChatMessagePayload)(nil), // 16: protobufs.BroadcastChatMessagePayload
	(*GameStateSyncPayload)(nil),        // 17: protobufs.GameStateSyncPayload
	nil,                                 // 18: protobufs.GameOverPayload.ScoresEntry
	(PowerUpType)(0),                    // 19: protobufs.PowerUpType
	(*PlayerData)(nil),                  // 20: protobufs.PlayerData
}
var file_payloads_proto_depIdxs = []int32{
	19, // 0: protobufs.UsePowerUpPayload.power_up_type:type_name -> protobufs.PowerUpType
	20, // 1: protobufs.PlayerJoinedPayload.player_data:type_name -> protobufs.PlayerData
	20, // 2: protobufs.PlayerDataUpdatePayload.player_data:type_name -> protobufs.PlayerData
	18, // 3: protobufs.GameOverPayload.scores:type_name -> protobufs.GameOverPayload.ScoresEntry
	20, // 4: protobufs.GameStateSyncPayload.players:type_name -> protobufs.PlayerData
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_payloads_proto_init() }
func file_payloads_proto_init() {
	if File_payloads_proto != nil {
		return
	}
	file_player_data_proto_init()
	file_power_up_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_payloads_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerJoinGamePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnectPlayerPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleReadyStatePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGamePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitWordPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsePowerUpPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessagePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnConnectAckPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerJoinedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLeftPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerDataUpdatePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStartedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TurnChangePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordValidationResultPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOverPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMessagePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastChatMessagePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStateSyncPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payloads_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payloads_proto_goTypes,
		DependencyIndexes: file_payloads_proto_depIdxs,
		MessageInfos:      file_payloads_proto_msgTypes,
	}.Build()
	File_payloads_proto = out.File
	file_payloads_proto_rawDesc = nil
	file_payloads_proto_goTypes = nil
	file_payloads_proto_depIdxs = nil
}
