syntax = "proto3";

package protobufs;

import "payloads.proto";

option go_package = "github.com/hue-go/atlas-backend/internal/protobufs";

enum ServerClientMessageType {
  S2C_UNKNOWN = 0;

  // Connection & Sync (100-199)
  ON_CONNECT_ACK = 101;
  GAME_STATE_SYNC = 102;

  // Player & Lobby Broadcasts (200-299)
  PLAYER_JOINED = 201;
  PLAYER_LEFT = 202;
  PLAYER_DATA_UPDATE = 203;

  // Game Flow Broadcasts (300-399)
  GAME_STARTED = 301;
  TURN_CHANGE = 302;
  GAME_OVER = 303;

  // Targeted Responses & Notifications (400-499)
  WORD_VALIDATION_RESULT = 401;
  ERROR_MESSAGE = 402;
  BROADCAST_CHAT_MESSAGE = 403;
}

message ServerClientMessage {
  ServerClientMessageType message_type = 1;
  oneof payload {
    OnConnectAckPayload on_connect_ack = 2;
    GameStateSyncPayload game_state_sync = 3;
    PlayerJoinedPayload player_joined = 4;
    PlayerLeftPayload player_left = 5;
    PlayerDataUpdatePayload player_data_update = 6;
    GameStartedPayload game_started = 7;
    TurnChangePayload turn_change = 8;
    WordValidationResultPayload word_validation_result = 9;
    GameOverPayload game_over = 10;
    ErrorMessagePayload error_message = 11;
    BroadcastChatMessagePayload broadcast_chat_message = 12;
  }
}
